framework:
    messenger:
        transports:
            sync: 'sync://'

        routing:
            App\Shared\Integration\Event\TransactionCreatedIntegrationEvent: sync
            App\Shared\Integration\Event\TransactionCompletedIntegrationEvent: sync
            App\Shared\Integration\Event\TransactionFailedIntegrationEvent: sync
            App\Account\Domain\Event\AccountCreatedEvent: sync
            App\Account\Domain\Event\MoneyDepositedEvent: sync
            App\Account\Domain\Event\MoneyWithdrawnEvent: sync
