framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default:
                default_middleware:
                    allow_no_handlers: true

        transports:
            sync: 'sync://'

        routing:
            App\Shared\Integration\Event\TransactionCreatedIntegrationEvent: sync
            App\Shared\Integration\Event\TransactionCompletedIntegrationEvent: sync
            App\Shared\Integration\Event\TransactionFailedIntegrationEvent: sync
            App\Account\Domain\Event\AccountCreatedEvent: sync
            App\Account\Domain\Event\MoneyDepositedEvent: sync
            App\Account\Domain\Event\MoneyWithdrawnEvent: sync
            App\User\Domain\Event\UserCreatedEvent: sync
            App\User\Domain\Event\UserEmailChangedEvent: sync
