framework:
    messenger:
        transports:
            sync: 'sync://'

        routing:
            App\Transaction\Domain\Event\TransactionCreatedEvent: sync
            App\Transaction\Domain\Event\TransactionCompletedEvent: sync
            App\Transaction\Domain\Event\TransactionFailedEvent: sync
